### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by Peedee2002** [Circles360/Circles360.github.io#4]
Soz if this isnt the right place to report it, but I found a few bugs

- [ ]  the scroll-wheel is broken if Firefox is used. That is - when I enter the planning phase, I cant scroll up and down the screen to see my degree progression, and am stuck staring at the graph. 

- [ ] trying to select COMP3900 (under the computer science graph) will white out the screen and make you have to write up everything again. I tested this multiple times and I think this is the broken button.

- [ ] for ENGG2600 and the rest, I think how it works is that you can enroll in the course 3 times over the year, not just once. 
ie - if you do VIP for one year, you enroll in 2600 in all those terms, not 2600 then 3600 then 4600 all in the same year. 
I may be wrong tho - but this is what i understood from the handbook's description of "multi-term course".

- [ ] MATH1081 incorrectly produces an error, as it is a co-requisite of 1131. the system seems to understand it as a prerequisite instead

The progress here looks awesome tho, and did genuinely help me understand more about what CSE offers. Thank you all so much!

**Comment by VincentXiao-jpg** [comment]
Thanks, we're glad that you've found our planner helpful. Unfortunately, the planner has only been tested on chrome, so some features may be broken on other browsers. For MATH1081, since 1131 is a co-req, having it be a pre-req is our current solution to representing that you need to have it selected to take 1081. COMP3900 should be fixed but ENGG2600 is a bit tricky, we're not too sure how to deal with it rn :/ We really appreciate your feedback and if you find any more bugs or have suggestions, please let us know.

**Comment by Peedee2002** [comment]
Thanks for the reply :) I do have a suggestion - is it possible to have a way block-out/change the cap for the number of units that can be automatically allocated to a term? This would be cool for students that want to use your automatic slotting and that arent necessarily going to always be full-time students.

**Comment by hayeselnut** [comment]
Hey Peedee2002,

This feature is currently in our backlog and we hope to implement it soon! Currently, however, we are prioritising on fixing our backend and making our overall product more stable (as you have seen :P ) before we move on to additional features. Another feature that we hope to implement soon is the ability to add years to the degree planner instead of having it fixed at 4, which would help out students who plan to take their degree over more years than usual.

In the mean time, you can manually arrange courses manually by dragging and dropping them into the terms you want. The UOC indicator will turn blue to confirm that the term is underloaded.
